In [1]:
import numpy as np
np.random.seed(7)
cities = np.array(["Kathmandu", "Pokhara", "Biratnagar", "Lalitpur", "Birgunj"])
days = np.array([f"D{i:02d}" for i in range(1, 15)])
temps = np.random.randint(14, 36, size=(5, 14)).astype(float)     
temps[2, 5] = np.nan     
# °C, 5 cities × 14 days
humidity = np.random.randint(40, 95, size=(5, 14)).astype(float)  # %
# sensor outage
temps[4, 11] = np.nan

### B1 — Array anatomy and reshaping (3 pts)
Print temps.shape , .ndim , .dtype , .size . Then build np.arange(70) , reshape it to the same shape as temps two ways — with explicit dimensions and with back. In a comment, explain what -1 — show the two results are identical, and flatten it-1 asked NumPy to work out, and why reshaping does not copy the data.

In [2]:
print("B1a-temps.shape:",temps.shape)

B1a-temps.shape: (5, 14)


In [3]:
print("B1b-temps.ndim:",temps.ndim)

B1b-temps.ndim: 2


In [4]:
print("B1c-temps datatype:",temps.dtype)

B1c-temps datatype: float64


In [5]:
print("B1d-temps size:",temps.size)

B1d-temps size: 70


In [6]:
arr=np.arange(70)

In [7]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69])

In [8]:
#Reshaping arr using explict dimension
reshape_explicit=arr.reshape(5,14)
reshape_explicit.shape

(5, 14)

In [9]:
#Reshaping arr with -1
reshape_auto=arr.reshape(5,-1)
reshape_auto.shape

(5, 14)

In [10]:
print("B1e- reshape with explicit dimensions:",reshape_explicit)
print("B1f-reshape with -1:",reshape_auto)

B1e- reshape with explicit dimensions: [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20 21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34 35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63 64 65 66 67 68 69]]
B1f-reshape with -1: [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20 21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34 35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63 64 65 66 67 68 69]]


In [11]:
print("B1g — reshapes are identical:", np.array_equal(
    reshape_explicit, reshape_auto
))

B1g — reshapes are identical: True


In [12]:
flatten=reshape_auto.flatten()

In [13]:
print("B1h-Flatten array:",flatten)
print("B1i-Flatten array",flatten.shape)

B1h-Flatten array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]
B1i-Flatten array (70,)


In [14]:
# -1 tells NumPy to calculate that dimension automatically.
# Reshape normally returns a view when possible, so it does not need to copy the underlying data; only the array's shape change.


## B2 — Indexing and slicing (4 pts)
Using indexing and slicing only, print: (a) Pokhara's day-3 temperature; (b) every city's reading on the last
day; (c) Biratnagar's full fortnight; (d) the block of the first three cities across days 4–8; (e) every other day for
Lalitpur; (f) Kathmandu's fortnight reversed. Print the shape alongside each result.

In [15]:
pokhara_day3_temps=temps[1,2]
print("B2a-Pokhara's day-3 temperature",pokhara_day3_temps)
print("B2a shape",np.shape(pokhara_day3_temps))

B2a-Pokhara's day-3 temperature 14.0
B2a shape ()


In [16]:
last_day_temperature=temps[:,-1]
print("B2b-Every city's reading on the last day",last_day_temperature)
print("B2b shape",last_day_temperature.shape)

B2b-Every city's reading on the last day [30. 28. 21. 18. 30.]
B2b shape (5,)


In [17]:
biratnagar_full_fortnight=temps[2,:]
print("B2c-Biratnagar's full fortnight",biratnagar_full_fortnight)
print("B2c shape",biratnagar_full_fortnight.shape)

B2c-Biratnagar's full fortnight [20. 18. 28. 23. 17. nan 22. 33. 30. 15. 14. 30. 26. 21.]
B2c shape (14,)


In [18]:
first_three_days_4_to_8=temps[:3,3:8]
print("B2d-The block of the first three cities across days 4-8")
print(first_three_days_4_to_8)
print("B2d shape",first_three_days_4_to_8.shape)

B2d-The block of the first three cities across days 4-8
[[33. 21. 28. 22. 28.]
 [25. 20. 33. 26. 19.]
 [23. 17. nan 22. 33.]]
B2d shape (3, 5)


In [19]:
lalitpur_every_other_day=temps[3,::2]
print("B2e-Every other day for Lalitpur",lalitpur_every_other_day)
print("B2e shape",lalitpur_every_other_day.shape)

B2e-Every other day for Lalitpur [24. 17. 21. 35. 17. 17. 33.]
B2e shape (7,)


In [20]:
kathmandu_fortnight_reversed=temps[0,::-1]
print("B2f-Kathmandu fortnight reversed temperature",kathmandu_fortnight_reversed)
print("B2f shape",kathmandu_fortnight_reversed.shape)

B2f-Kathmandu fortnight reversed temperature [30. 18. 20. 21. 22. 24. 28. 22. 28. 21. 33. 17. 18. 29.]
B2f shape (14,)


## B3 — Boolean masks (3 pts)
(a) Build the mask temps > 30 and print how many readings exceed 30 per city — one number per city, no loop.

(b) Print the actual day labels on which Kathmandu exceeded 30, by using the mask to index days .

(c)In a comment, explain in one sentence what a mask is, and why temps[temps > 30] cannot keep the 2D shape.

In [21]:
mask=temps>30
print("B3a-no of readings exceed 30 per city",np.sum(mask,axis=1))


B3a-no of readings exceed 30 per city [1 2 1 2 6]


In [22]:
kathmandu_hot_days=days[mask[0]]
print("B3b-actual day label on which kathmandu exceeded 30:",kathmandu_hot_days)

B3b-actual day label on which kathmandu exceeded 30: ['D04']


In [23]:
# A mask is an array of True/False values used to select elements.
# temps[temps > 30] returns only selected values, so the original 2D structure is lost and the result becomes a 1D array.


## B4 — Views vs. copies (3 pts)

Take a slice of one city's first three days, set its first element to 999 , and print the original array to prove it changed. Repeat with .copy() and prove it did not. In a comment, explain in two sentences why NumPy defaults to a view, and what bug this causes if you forget.

In [24]:
sliced_first_three_days=temps[0,:3]
sliced_first_three_days[0]=999
print("B4a-Original array after modifying view:")
print(temps)


B4a-Original array after modifying view:
[[999.  18.  17.  33.  21.  28.  22.  28.  24.  22.  21.  20.  18.  30.]
 [ 21.  26.  14.  25.  20.  33.  26.  19.  35.  30.  14.  16.  23.  28.]
 [ 20.  18.  28.  23.  17.  nan  22.  33.  30.  15.  14.  30.  26.  21.]
 [ 24.  23.  17.  14.  21.  14.  35.  18.  17.  15.  17.  15.  33.  18.]
 [ 33.  15.  19.  23.  31.  16.  33.  32.  32.  35.  17.  nan  29.  30.]]


In [25]:
#reseting the acutal previous value after work
temps[0,0]=29

In [26]:
copied_first_three_days=temps[0,:3].copy()

In [27]:
copied_first_three_days[0]=999

In [28]:
print("B4b-Original array after modifying copy:")
print(temps)

B4b-Original array after modifying copy:
[[29. 18. 17. 33. 21. 28. 22. 28. 24. 22. 21. 20. 18. 30.]
 [21. 26. 14. 25. 20. 33. 26. 19. 35. 30. 14. 16. 23. 28.]
 [20. 18. 28. 23. 17. nan 22. 33. 30. 15. 14. 30. 26. 21.]
 [24. 23. 17. 14. 21. 14. 35. 18. 17. 15. 17. 15. 33. 18.]
 [33. 15. 19. 23. 31. 16. 33. 32. 32. 35. 17. nan 29. 30.]]


In [29]:
# Numpy uses views for slicing operations because doing this so make memory efficient.
#If we forget this view concept, modifying sliced data update our original dataset and affects our data operations


## B5 — Vectorization vs. a Python loop (4 pts)
Convert temps to Fahrenheit two ways: with an explicit loop (the only loop allowed in Part B) and with one vectorized expression. Confirm they agree with np.allclose. Then time both on an array of 1,000,000 values using time.perf_counter(), and print both timings plus the speedup as a multiple (~Nx faster ). In a comment, explain where the loop's extra time actually goes

In [34]:
fahrenheit_loop=np.empty_like(temps)
for i in range(temps.shape[0]):
    for j in range(temps.shape[1]):
        fahrenheit_loop[i, j] = (temps[i, j] * 9 / 5) + 32

In [35]:
# Vectorized expression
fahrenheit_vectorized = (temps * 9 / 5) + 32

In [36]:
print("B5a — Loop and vectorized results agree:",
      np.allclose(fahrenheit_loop, fahrenheit_vectorized, equal_nan=True))

B5a — Loop and vectorized results agree: True


In [37]:
# Timing on 1,000,000 values
large_values = np.random.randint(14, 36, size=1_000_000).astype(float)

In [38]:
start_loop = __import__("time").perf_counter()

large_fahrenheit_loop = np.empty_like(large_values)

for i in range(large_values.size):
    large_fahrenheit_loop[i] = (large_values[i] * 9 / 5) + 32

loop_time = __import__("time").perf_counter() - start_loop

In [39]:
start_vectorized = __import__("time").perf_counter()

large_fahrenheit_vectorized = (large_values * 9 / 5) + 32

vectorized_time = __import__("time").perf_counter() - start_vectorized

In [40]:
speedup = loop_time / vectorized_time

In [41]:
print("B5b — Loop timing:", loop_time, "seconds")
print("B5c — Vectorized timing:", vectorized_time, "seconds")
print("B5d — Vectorization speedup: ~", speedup, "x")

B5b — Loop timing: 1.12146009999924 seconds
B5c — Vectorized timing: 0.010686400000849972 seconds
B5d — Vectorization speedup: ~ 104.94274029701691 x


In [42]:
# The loop spends extra time repeatedly executing Python-level iteration, indexing, and assignment, while NumPy performs the arithmetic in optimized compiled code over the whole array.

## B6 — Broadcasting (4 pts)

(a) Compute each city's own fortnight average with a NaN-aware function and 
keepdims=True 
, then
subtract it from 
temps
 to get an anomaly grid; print the result's shape and confirm it is still 
(5, 14) 
. (b)
Apply a per-day sensor correction of shape 
(14,)
 to all five cities in one expression. (c) Attempt 
np.array([1, 2, 3, 4, 5]) 
, catch the 
temps +
ValueError 
, print its message, and explain in a comment why
aligning shapes from the right makes this fail while (b) succeeds.

In [43]:
city_averages = np.nanmean(temps, axis=1, keepdims=True)

anomaly_grid = temps - city_averages

print("B6a — Anomaly grid shape:", anomaly_grid.shape)
print("B6a — Is shape still (5, 14)?", anomaly_grid.shape == (5, 14))

B6a — Anomaly grid shape: (5, 14)
B6a — Is shape still (5, 14)? True


In [44]:
# One correction value for each of the 14 days.
sensor_correction = np.array([
    0.2, -0.1, 0.3, 0.0, -0.2, 0.1, 0.4,
    -0.3, 0.2, 0.1, -0.1, 0.3, 0.0, -0.2
])

corrected_temps = temps + sensor_correction

print("B6b — Corrected temperature grid shape:", corrected_temps.shape)
print("B6b — Corrected temperatures:")
print(corrected_temps)

B6b — Corrected temperature grid shape: (5, 14)
B6b — Corrected temperatures:
[[29.2 17.9 17.3 33.  20.8 28.1 22.4 27.7 24.2 22.1 20.9 20.3 18.  29.8]
 [21.2 25.9 14.3 25.  19.8 33.1 26.4 18.7 35.2 30.1 13.9 16.3 23.  27.8]
 [20.2 17.9 28.3 23.  16.8  nan 22.4 32.7 30.2 15.1 13.9 30.3 26.  20.8]
 [24.2 22.9 17.3 14.  20.8 14.1 35.4 17.7 17.2 15.1 16.9 15.3 33.  17.8]
 [33.2 14.9 19.3 23.  30.8 16.1 33.4 31.7 32.2 35.1 16.9  nan 29.  29.8]]


In [46]:
try:
    invalid_result = temps + np.array([1, 2, 3, 4, 5])
except ValueError as error:
    print("B6c — Broadcasting ValueError:", error)

B6c — Broadcasting ValueError: operands could not be broadcast together with shapes (5,14) (5,) 


In [47]:
# Broadcasting aligns dimensions from the right. A (5,) array cannot match the final dimension of temps, which is 14, while the (14,) correction in part (b) matches the 14-day dimension and can therefore broadcast across rows.

## B7 — Matrix multiplication (4 pts)
(a) On the grocery-basket example (
quantities = [2, 3, 1] 
, 
prices = [120, 90, 250] 
), print both 
and 
@
, and state in a comment what each returned and why they differ. (b) Build 
features
 of shape 
*
(14,
2)
 whose columns are the across-city NaN-aware mean temperature and mean humidity per day, define
weights = np.array([0.6, -0.1]) 
, and compute a comfort score per day with 
@ 
. Print the shapes of
features 
, 
weights 
, and the result, and explain in a comment why the inner dimensions had to match.

In [48]:
quantities = np.array([2, 3, 1])
prices = np.array([120, 90, 250])

print("B7a — quantities * prices:", quantities * prices)
print("B7a — quantities @ prices:", quantities @ prices)

# * performs element-by-element multiplication and returns an array.
# @ performs dot/matrix multiplication and returns the total weighted sum.

B7a — quantities * prices: [240 270 250]
B7a — quantities @ prices: 760


In [49]:
features = np.column_stack([
    np.nanmean(temps, axis=0),
    np.nanmean(humidity, axis=0)
])

weights = np.array([0.6, -0.1])

comfort_scores = features @ weights

print("B7b — features shape:", features.shape)
print("B7b — weights shape:", weights.shape)
print("B7b — comfort scores shape:", comfort_scores.shape)
print("B7b — comfort scores:", comfort_scores)


B7b — features shape: (14, 2)
B7b — weights shape: (2,)
B7b — comfort scores shape: (14,)
B7b — comfort scores: [ 9.06  5.32  4.16  6.58  5.06  6.39  9.16  8.74 11.26  7.22  2.6   6.43
  8.66  8.16]


In [50]:
# Matrix multiplication requires the inner dimensions to match: (14, 2) @ (2,) produces one score for each of the 14 days.

## B8 — Aggregating along an axis (4 pts)
Using NaN-aware aggregations, print: mean, max, min and std per city; mean and max per day; and each
city's hottest day as a day label (use 
argmax 
, then index 
days 
). State each result's shape. In a comment,
state what 
axis=0
 and 
axis=1
 collapse here, in terms of this dataset.

In [51]:
city_mean = np.nanmean(temps, axis=1)
city_max = np.nanmax(temps, axis=1)
city_min = np.nanmin(temps, axis=1)
city_std = np.nanstd(temps, axis=1)

print("B8a — Mean temperature per city:", city_mean)
print("B8a shape:", city_mean.shape)

print("B8b — Maximum temperature per city:", city_max)
print("B8b shape:", city_max.shape)

print("B8c — Minimum temperature per city:", city_min)
print("B8c shape:", city_min.shape)

print("B8d — Temperature std per city:", city_std)
print("B8d shape:", city_std.shape)

B8a — Mean temperature per city: [23.64285714 23.57142857 22.84615385 20.07142857 26.53846154]
B8a shape: (5,)
B8b — Maximum temperature per city: [33. 35. 33. 35. 35.]
B8b shape: (5,)
B8c — Minimum temperature per city: [17. 14. 14. 14. 15.]
B8c shape: (5,)
B8d — Temperature std per city: [4.89324816 6.41108733 5.89453663 6.41943796 7.11028924]
B8d shape: (5,)


In [52]:
day_mean = np.nanmean(temps, axis=0)
day_max = np.nanmax(temps, axis=0)

print("B8e — Mean temperature per day:", day_mean)
print("B8e shape:", day_mean.shape)

print("B8f — Maximum temperature per day:", day_max)
print("B8f shape:", day_max.shape)

B8e — Mean temperature per day: [25.4  20.   19.   23.6  22.   22.75 27.6  26.   27.6  23.4  16.6  20.25
 25.8  25.4 ]
B8e shape: (14,)
B8f — Maximum temperature per day: [33. 26. 28. 33. 31. 33. 35. 33. 35. 35. 21. 30. 33. 30.]
B8f shape: (14,)


In [53]:
hottest_day_indices = np.nanargmax(temps, axis=1)
hottest_days = days[hottest_day_indices]

print("B8g — Hottest day for each city:", hottest_days)
print("B8g shape:", hottest_days.shape)

B8g — Hottest day for each city: ['D04' 'D09' 'D08' 'D07' 'D10']
B8g shape: (5,)


In [54]:
# axis=0 collapses the city dimension, producing one result per day.
# axis=1 collapses the day dimension, producing one result per city.


## B9 — Reproducible randomness and a train/test split (3 pts)
Flatten 
temps
 to 70 samples. With 
np.random.seed(42) 
, shuffle an index array and split it 80/20 into train
and test index sets; print both shapes, confirm they sum to 70, and confirm they share no index. Re-seed with
42, repeat, and assert the split is identical. In a comment, explain why you shuffle before splitting, and why
the seed matters when you share results

In [55]:
flat_temps = temps.flatten()

In [56]:
np.random.seed(42)

indices = np.arange(flat_temps.size)
np.random.shuffle(indices)

split_point = int(0.8 * len(indices))

train_indices = indices[:split_point]
test_indices = indices[split_point:]

In [57]:
print("B9a — Train index shape:", train_indices.shape)
print("B9b — Test index shape:", test_indices.shape)
print("B9c — Total samples:", train_indices.size + test_indices.size)
print("B9d — Total is 70:", train_indices.size + test_indices.size == 70)
print("B9e — Train/test share no index:",
      np.intersect1d(train_indices, test_indices).size == 0)


B9a — Train index shape: (56,)
B9b — Test index shape: (14,)
B9c — Total samples: 70
B9d — Total is 70: True
B9e — Train/test share no index: True


In [58]:
# Repeat with the same seed.
np.random.seed(42)

indices_repeat = np.arange(flat_temps.size)
np.random.shuffle(indices_repeat)

split_point_repeat = int(0.8 * len(indices_repeat))

train_indices_repeat = indices_repeat[:split_point_repeat]
test_indices_repeat = indices_repeat[split_point_repeat:]

In [59]:
print("B9f — Split is identical after reseeding:",
      np.array_equal(train_indices, train_indices_repeat)
      and np.array_equal(test_indices, test_indices_repeat))

assert np.array_equal(train_indices, train_indices_repeat)
assert np.array_equal(test_indices, test_indices_repeat)

B9f — Split is identical after reseeding: True


In [60]:
# Shuffling before splitting helps avoid depending on the original ordering of the data. The seed makes the random shuffle reproducible so others can recreate the same train/test split when checking or sharing results.

## B10 — np.where , argmax , argmin (3 pts)
(a) Label every reading "hot" / "mild" / "cold" (above 30, 22–30, below 22) with nested np.where , and print the label grid's shape. 
(b) Given scores = np.array([0.08, 0.62, 0.21, 0.09]) and labels=["rain", "clear", "cloudy", "fog"] , print the predicted label using argmax. In a comment, explain why a classifier needs argmax rather than max.

In [63]:
temperature_labels = np.where(
    temps > 30,
    "hot",
    np.where(
        temps >= 22,
        "mild",
        "cold"
    )
)

print("B10a — Temperature label grid:")
print(temperature_labels)
print("B10a — Label grid shape:", temperature_labels.shape)

B10a — Temperature label grid:
[['mild' 'cold' 'cold' 'hot' 'cold' 'mild' 'mild' 'mild' 'mild' 'mild'
  'cold' 'cold' 'cold' 'mild']
 ['cold' 'mild' 'cold' 'mild' 'cold' 'hot' 'mild' 'cold' 'hot' 'mild'
  'cold' 'cold' 'mild' 'mild']
 ['cold' 'cold' 'mild' 'mild' 'cold' 'cold' 'mild' 'hot' 'mild' 'cold'
  'cold' 'mild' 'mild' 'cold']
 ['mild' 'mild' 'cold' 'cold' 'cold' 'cold' 'hot' 'cold' 'cold' 'cold'
  'cold' 'cold' 'hot' 'cold']
 ['hot' 'cold' 'cold' 'mild' 'hot' 'cold' 'hot' 'hot' 'hot' 'hot' 'cold'
  'cold' 'mild' 'mild']]
B10a — Label grid shape: (5, 14)


In [64]:
scores = np.array([0.08, 0.62, 0.21, 0.09])
labels = np.array(["rain", "clear", "cloudy", "fog"])

predicted_index = np.argmax(scores)
predicted_label = labels[predicted_index]

print("B10b — Predicted label:", predicted_label)
print("B10b — Predicted index:", predicted_index)


B10b — Predicted label: clear
B10b — Predicted index: 1


In [65]:
# argmax returns the position of the largest score, which lets us use that position to select the corresponding label. max() returns only the value, so it cannot directly tell us which label produced that value.