# NumPy Foundations

**Arrays · Indexing and Slicing · Vectorized Operations · Broadcasting**

Instructor: Netra Prasad Neupane

---

This notebook goes with the class slides, and uses the same running example throughout: a week of
daily temperatures (in °C) for three Nepali cities. Every idea is introduced with a short explanation
first, then a small piece of code you can run and change yourself. Read a cell, run it (Shift+Enter),
look at the output, and make sure it matches what you expected *before* moving to the next cell.


In [1]:
import numpy as np

# The dataset we'll use for the whole notebook: one week of temperatures (°C)
temps = np.array([22, 24, 19, 21, 26, 28, 23])  # Kathmandu, Mon -> Sun

grid = np.array([
    [22, 24, 19, 21, 26, 28, 23],   # Kathmandu
    [24, 25, 22, 23, 27, 29, 25],   # Pokhara
    [28, 29, 27, 28, 31, 33, 30],   # Biratnagar
])

days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
cities = ["Kathmandu", "Pokhara", "Biratnagar"]

print(temps)
print(grid)

[22 24 19 21 26 28 23]
[[22 24 19 21 26 28 23]
 [24 25 22 23 27 29 25]
 [28 29 27 28 31 33 30]]


## Module 1 — Creating and Working with NumPy Arrays

### Why do we need NumPy?

**NumPy** is short for **Numerical Python** — a library built specifically for fast, memory-efficient
work with numbers.

A Python list is flexible — it can hold anything, in any order, and grow or shrink freely. That
flexibility has a real cost for numerical work: every number in a list is its own Python object,
sitting at its own address in memory, and Python has to check what type of object it is every single
time you touch it.

NumPy's core object, the **`ndarray`** ("n-dimensional array"), takes a different approach: it stores
a grid of values that are *all the same type*, packed together in one contiguous block of memory.
That single design choice — same type, stored together — is what makes NumPy fast enough for
real numerical and machine learning work.


In [2]:
# A Python list of temperatures
py_list = [22, 24, 19, 21, 26, 28, 23]
print(type(py_list), py_list)

# The same data as a NumPy array
np_array = np.array(py_list)
print(type(np_array), np_array)

<class 'list'> [22, 24, 19, 21, 26, 28, 23]
<class 'numpy.ndarray'> [22 24 19 21 26 28 23]


Notice the array prints without commas — that's your first visual cue that this is not a
Python list. Under the hood, every one of those numbers is stored as a plain 64-bit integer, right
next to its neighbors, rather than as a separate Python object.


### Creating arrays from data you already have

The most common way to build an array is `np.array()`, given a list (for a 1D array) or a list of
lists (for a 2D array — one inner list per row).


In [3]:
temps = np.array([22, 24, 19, 21, 26, 28, 23])
print(temps)

grid = np.array([
    [22, 24, 19, 21, 26, 28, 23],   # Kathmandu
    [24, 25, 22, 23, 27, 29, 25],   # Pokhara
    [28, 29, 27, 28, 31, 33, 30],   # Biratnagar
])
print(grid)

[22 24 19 21 26 28 23]
[[22 24 19 21 26 28 23]
 [24 25 22 23 27 29 25]
 [28 29 27 28 31 33 30]]


### Creating arrays without typing every value

Often you don't have the data yet — you need a placeholder, a counter, or an evenly spaced range.
NumPy has built-in generators for exactly this:

| Function | Example | What it gives you |
|---|---|---|
| `np.zeros(n)` | `np.zeros(7)` | a blank week, all zeros, ready to fill in |
| `np.ones((r, c))` | `np.ones((3, 7))` | a grid of 1s, the same shape as our data |
| `np.arange(start, stop)` | `np.arange(0, 7)` | day indices 0–6, like Python's `range()` |
| `np.linspace(start, stop, n)` | `np.linspace(0, 1, 5)` | 5 evenly spaced points between 0 and 1 |


In [4]:
print("zeros(7)      :", np.zeros(7))
print("ones((3,7))\n", np.ones((3, 7)))
print("arange(0,7)  :", np.arange(0, 7))
print("linspace(0,1,5):", np.linspace(0, 1, 5))

zeros(7)      : [0. 0. 0. 0. 0. 0. 0.]
ones((3,7))
 [[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
arange(0,7)  : [0 1 2 3 4 5 6]
linspace(0,1,5): [0.   0.25 0.5  0.75 1.  ]


### Every array knows its own shape and type

Four attributes you will use constantly: `shape`, `ndim`, `dtype`, and `size`.


In [5]:
print("shape:", grid.shape)  # (rows, columns) -> 3 cities, 7 days
print("ndim :", grid.ndim)   # number of dimensions
print("dtype:", grid.dtype)  # the single type shared by every element
print("size :", grid.size)   # total number of values (3 x 7 = 21)

shape: (3, 7)
ndim : 2
dtype: int64
size : 21


### Reshaping arrays

Reshaping does **not** move or copy the underlying values — it changes how the same block of memory
is *viewed*. That's why the total number of values must stay the same before and after.


In [6]:
flat = np.arange(1, 22)          # 21 numbers in a single row
print("flat:", flat, "shape:", flat.shape)

reshaped = flat.reshape(3, 7)     # the same 21 numbers, viewed as 3 rows of 7
print(reshaped)
print("shape:", reshaped.shape)

back_to_flat = reshaped.flatten()  # reverses it
print("flattened again:", back_to_flat)

flat: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21] shape: (21,)
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]
shape: (3, 7)
flattened again: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]


You can also let NumPy work out one of the dimensions for you, with `-1`: "reshape this into 3
rows, and figure out how many columns that requires."


In [7]:
auto = flat.reshape(3, -1)   # -1 means figure out this dimension -- NumPy computes 7
print(auto.shape)

(3, 7)


**Try it yourself:** create an array with `np.arange(0, 12)` and reshape it into a `(3, 4)` grid,
then into a `(4, 3)` grid. What happens if you try `.reshape(3, 5)`? Run it and read the error message —
it tells you exactly what went wrong.


In [8]:
# Your code here


## Module 2 — Indexing and Slicing Arrays

### Getting one value out of an array

Just like Python lists, you index from the front with `0, 1, 2, ...`, or count backward from the end
with `-1, -2, ...`.


In [9]:
print(temps[0])    # 22  -> Monday
print(temps[-1])   # 23  -> Sunday (last element)
print(temps[3])    # 21  -> Thursday

# For a 2D array, give both the row and the column
print(grid[0, 3])  # Kathmandu's Thursday temperature

22
23
21
21


### Slicing: getting a range at once

The slicing syntax is `array[start:stop:step]`. As with Python lists, `stop` is **not** included. If
you skip `start` or `stop`, Python fills in a default for you: no `start` defaults to "the beginning,"
and no `stop` defaults to "the end."


In [10]:
print(temps[1:5])    # Tue, Wed, Thu, Fri  (index 5 is excluded)
print(temps[:3])     # Mon, Tue, Wed          (from the start)
print(temps[4:])     # Fri, Sat, Sun          (to the end)
print(temps[::2])    # every other day: Mon, Wed, Fri, Sun
print(temps[::-1])   # the whole week, reversed

[24 19 21 26]
[22 24 19]
[26 28 23]
[22 19 26 23]
[23 28 26 21 19 24 22]


### Slicing a 2D grid: rows, columns, and blocks

The same idea extends to two dimensions — just separate the row slice and the column slice with a
comma. A bare `:` means "everything along this axis."


In [11]:
print("Kathmandu, all days:      ", grid[0, :])       # row 0, every column
print("Monday, all cities:      ", grid[:, 0])        # every row, column 0
print("2 cities, Wed-Fri:\n", grid[0:2, 2:5])          # rows 0-1, columns 2-4

Kathmandu, all days:       [22 24 19 21 26 28 23]
Monday, all cities:       [22 24 28]
2 cities, Wed-Fri:
 [[19 21 26]
 [22 23 27]]


### Selecting values by condition (boolean indexing)

A comparison like `temps > 24` doesn't return a single answer — it returns an array of the *same
shape*, full of `True`/`False` values. This is called a **mask**. Feeding that mask back into the
array as an index selects only the positions where it's `True`.


In [12]:
mask = temps > 24
print("mask :", mask)
print("hits :", temps[mask])

# usually written in one line:
print(temps[temps > 24])   # "which days were warmer than 24 degrees?"

# works the same way on the 2D grid
print(grid[grid >= 28])    # every reading, from any city, at or above 28

mask : [False False False False  True  True False]
hits : [26 28]
[26 28]
[28 29 28 29 28 31 33 30]


### An important gotcha: views vs. copies

Slicing gives you back a **view**: a new array object, but one whose data pointer, shape, and
strides all describe a window into the *original* array's data buffer, rather than an independent
copy of the values. Change a value through the view, and the original array changes too — you're
both looking at (and writing to) the exact same block of memory. This is a common surprise the first
time you meet it, so it's worth seeing deliberately, once, right now.


In [13]:
# a fresh array just for this demo, so we don't disturb `temps` for later cells
demo = np.array([22, 24, 19, 21, 26, 28, 23])

first_three = demo[0:3]
print("before:", demo)

first_three[0] = 100     # modifying the slice...
print("after: ", demo)   # ...also changed the original array!

# when you actually want an independent copy, ask for one explicitly:
safe_copy = demo[0:3].copy()
safe_copy[0] = -1
print("demo is unaffected:", demo)

before: [22 24 19 21 26 28 23]
after:  [100  24  19  21  26  28  23]
demo is unaffected: [100  24  19  21  26  28  23]


**Try it yourself:** using `grid`, select every temperature reading from Pokhara that was above
25°C. Then check whether slicing `grid[1, :]` and modifying an element affects `grid` itself.


In [ ]:
# Your code here


## Module 3 — Vectorized Operations

### The problem with writing your own loop

Say we want to convert the week's Celsius readings to Fahrenheit. Here are two ways to do it.


In [3]:
# The loop way
fahrenheit_loop = []
for c in temps:
    fahrenheit_loop.append(c * 9 / 5 + 32)
print(fahrenheit_loop)

# The vectorized way
fahrenheit_vec = temps * 9 / 5 + 32
print(fahrenheit_vec)

[np.float64(71.6), np.float64(75.2), np.float64(66.2), np.float64(69.8), np.float64(78.8), np.float64(82.4), np.float64(73.4)]
[71.6 75.2 66.2 69.8 78.8 82.4 73.4]


Same result, one short line. This isn't just about tidier code — it's genuinely faster, and the
gap grows enormously as the data gets bigger. Let's actually measure it, rather than take that on
faith.


In [4]:
import timeit

n = 1_000_000
a = list(range(n))
b = list(range(n))
na = np.arange(n)
nb = np.arange(n)

def loop_add():
    out = [0] * n
    for i in range(n):
        out[i] = a[i] + b[i]
    return out

def vectorized_add():
    return na + nb

loop_time = timeit.timeit(loop_add, number=3) / 3
vec_time = timeit.timeit(vectorized_add, number=3) / 3

print(f"loop:       {loop_time:.4f} s")
print(f"vectorized: {vec_time:.5f} s")
print(f"speedup:    {loop_time / vec_time:.0f}x  (adding two arrays of {n:,} numbers)")

loop:       0.0453 s
vectorized: 0.00113 s
speedup:    40x  (adding two arrays of 1,000,000 numbers)


### What "vectorized" actually means

A vectorized operation applies the same calculation to *every element at once* — without you writing
the loop. NumPy still loops internally, but it does so in compiled code, over one contiguous block of
memory, without Python's per-element overhead.

This works for ordinary arithmetic between two arrays of the same shape, too:


In [ ]:
print(temps + 5)          # 5 degrees warmer, every day, in one step
print(temps * 2)          # double every value

# how much did the temperature change from one day to the next?
print(temps[1:] - temps[:-1])   # array of 6 differences

### Built-in vectorized functions

NumPy ships with vectorized math functions (called **ufuncs**, short for "universal functions") that
apply to every element, plus **aggregate** functions that summarize a whole array into a single
number.


In [ ]:
print("sqrt        :", np.sqrt(temps))
print("abs of diffs:", np.abs(temps[1:] - temps[:-1]))
print()
print("mean (average):", temps.mean())
print("max (hottest) :", temps.max())
print("min (coldest) :", temps.min())
print("std (spread)  :", temps.std())

**Try it yourself:** compute the average temperature for *each city* in `grid` (hint: look up
the `axis` argument for `.mean()` — `axis=1` means "average across the columns, for each row").


In [ ]:
# Your code here


## Module 4 — Broadcasting

### The problem: what if the shapes don't match?

We already broadcast without naming it: `temps + 5` takes a single number (a *scalar*) and applies it
to all 7 values — NumPy "stretches" the scalar to match the array's shape. Broadcasting is the general
version of that rule, for combining arrays whose shapes don't match exactly, but are *compatible*.

Suppose each day has its own sensor correction, and we want to apply it to all three cities' readings
at once.


In [ ]:
correction = np.array([1, 0, -1, 0, 1, 0, -1])   # shape (7,)
print("grid shape:      ", grid.shape)
print("correction shape:", correction.shape)

corrected = grid + correction     # shape (7,) broadcasts across all 3 rows of shape (3, 7)
print(corrected)

### The broadcasting rule, in plain terms

To decide whether two shapes can combine, NumPy lines them up **from the right** and compares them
dimension by dimension. Two dimensions are compatible when they are equal, or when one of them is 1
(a missing dimension counts as 1) — a size-1 dimension is the one that stretches to match.

```
grid        (3, 7)
correction     (7,)
             ------
result      (3, 7)
```

`7` matches `7`. `correction` has no size in the first position, so it's treated as `1`, which
stretches to cover all 3 rows.

A few more examples, worked out the same way:

| Shape A | Shape B | Compatible? | Result |
|---|---|---|---|
| (3, 7) | (7,) | yes | (3, 7) |
| (3, 7) | (3, 1) | yes | (3, 7) |
| (3, 7) | (3,) | **no** | error |


In [ ]:
# The third row of that table, deliberately triggering the error --
# uncomment the line below and run it to see NumPy's own explanation.

# grid + np.array([1, 2, 3])

### Worked example: how far off is each city's average?

Let's subtract each city's *own* weekly average from its daily readings — no loop over cities needed.


In [ ]:
city_avg = grid.mean(axis=1, keepdims=True)   # shape (3, 1) -- one average per city
print("city_avg shape:", city_avg.shape)
print(city_avg)

difference = grid - city_avg                   # (3, 7) and (3, 1) broadcast to (3, 7)
print(difference.round(1))

Here, `city_avg` has shape `(3, 1)`: one value per row, and a size-1 second dimension. Lined up
against `grid`'s `(3, 7)`, the `1` stretches across all 7 columns, so each city's average is subtracted
from every one of its own daily readings — automatically, with no loop over cities.

**Try it yourself:** without running it yet, predict the shape of `grid - grid.mean(axis=0)`
(note: `axis=0` this time). Then run it and check your answer — what does subtracting *this* mean
represent, in plain language?


In [ ]:
# Your code here


## Wrapping up · Part 1

Four ideas to take with you so far:

- **Arrays** store same-typed values together in one block of memory — that's the whole reason NumPy
  is fast.
- **Indexing and slicing** let you grab exactly the values you need — one element, a range, a row, a
  column, or by condition — usually as a *view* onto the same data, not a copy.
- **Vectorized operations** replace explicit loops with whole-array operations that run as compiled
  code instead of Python bytecode.
- **Broadcasting** lets arrays of different (but compatible) shapes combine automatically, by aligning
  their dimensions from the right.

Everything above used one dataset — a week of temperatures for three cities — on purpose: the same
four ideas apply, unchanged, to any array of numbers you'll work with later in this course, whether
that's a dataset of a thousand rows or a batch of images.

The four ideas above are the foundation. The five sections below show up in the very next thing
you'll learn — regression, classification, or a first neural network — so we're covering them now
rather than later.


## Module 5 — Matrix Multiplication

### Not the same as multiplying element by element

`a * b` multiplies matching positions together — element by element, same shape in, same shape out.
Matrix multiplication (`a @ b`) is a different operation: it multiplies pairs of numbers together and
**adds them up**, collapsing two arrays down to something smaller. In NumPy, `*` is elementwise
multiplication and `@` is matrix multiplication — they are not interchangeable, and using the wrong
one silently gives you a wrong-shaped (or wrong-valued) answer instead of an error.


In [ ]:
a = np.array([2, 3, 1])
b = np.array([10, 10, 10])

print("elementwise a * b:", a * b)   # [20, 30, 10] -- same shape as a and b
print("matrix a @ b:     ", a @ b)   # 60           -- a single number

### A dot product is just a weighted total

The simplest matrix multiplication is a **dot product**: multiply each pair of numbers, then add
everything up. Here it is with a grocery basket — quantities of three items, and their prices.


In [ ]:
quantities = np.array([2, 3, 1])          # 2 kg rice, 3 kg lentils, 1 liter oil
prices     = np.array([120, 90, 250])     # price per unit, in Rs.

total = quantities @ prices
print("total cost: Rs.", total)

# spelled out, this is exactly:
print("by hand:   ", 2*120 + 3*90 + 1*250)

`quantities @ prices` multiplies each quantity by its own price, then adds the three results
together. This exact pattern — multiply each input by its own weight, then add — is what a single
neuron computes, and what linear regression fits.

### From one basket to a whole table of days

Give each day two features instead of one — temperature and humidity — and a weight for each.
Matrix multiplication scores every day at once, no loop required.


In [ ]:
humidity = np.array([55, 60, 70, 65, 50, 45, 58])   # a plausible companion to temps, % humidity

features = np.column_stack([temps, humidity])   # shape (7, 2) -- one row per day, two columns
weights  = np.array([0.6, -0.1])                # shape (2,)   -- one weight per feature

comfort_score = features @ weights              # shape (7,)  -- one score per day
print("features shape:", features.shape)
print("comfort_score: ", comfort_score.round(1))

Each day's score is its own dot product: `0.6 * temp - 0.4 * humidity`. `features @ weights`
computes all 7 of those dot products in a single call — this is precisely what "a linear layer" or
"linear regression" means once you strip away the vocabulary.

**Try it yourself:** add a third feature of your choosing (e.g. `wind_speed`, made up), give it a
weight, and recompute `comfort_score`. What has to change about `weights` for the `@` to still work?


In [ ]:
# Your code here


## Module 6 — Aggregating Along an Axis

`grid` has shape `(3, 7)` — 3 cities, 7 days. Every aggregation function (`sum`, `mean`, `max`, `min`,
`std`, `argmax`, ...) accepts an `axis` argument that controls *which direction collapses*:

- `axis=0` walks **down the rows** — it collapses the cities, leaving one number per day.
- `axis=1` walks **across the columns** — it collapses the days, leaving one number per city.

**Rule of thumb: `axis=N` is the dimension that disappears from the result.**


In [ ]:
print("axis=0, one number per day: ", grid.sum(axis=0))   # shape (7,)
print("axis=1, one number per city:", grid.sum(axis=1))   # shape (3,)

The same `axis` argument works the same way on every aggregation function:

In [ ]:
print("total per city:        ", grid.sum(axis=1))
print("average per city:      ", grid.mean(axis=1).round(1))
print("hottest city, per day: ", grid.max(axis=0))
print("coolest day, per city: ", grid.min(axis=1))
print("variation per city:    ", grid.std(axis=1).round(1))
print("hottest day (index):   ", grid.argmax(axis=1))   # a POSITION, not a value -- more in Module 8

**Try it yourself:** which city had the *smallest* range between its hottest and coolest day
this week? (Hint: `grid.max(axis=1) - grid.min(axis=1)`, then find which position holds the smallest
value.)


In [ ]:
# Your code here


## Module 7 — Random Numbers

`np.random.seed(...)` fixes the starting point of NumPy's random number generator. With the same
seed, you get the exact same "random" numbers every time you re-run the code — essential when you
need to debug something or let someone else reproduce your results.


In [ ]:
np.random.seed(42)

print(np.random.rand(3))               # 3 floats, uniform in [0, 1)
print(np.random.randn(3))               # 3 floats, standard normal (mean 0, std 1)
print(np.random.randint(0, 10, size=3)) # 3 integers, 0-9

# Re-run this cell: the seed is set again each time, so you'll see the same three lines every time.

`rand` gives you uniform noise or randomly-initialized weights. `randn` gives you normally
distributed noise. `randint` gives you random integers — useful for labels or indices.

### Shuffling and sampling: the core of a train/test split

Before training a model, you split your data into a training set and a test set — and you need to
shuffle first, so both sets end up a fair mix rather than, say, all of one city's days landing in the
same set.


In [ ]:
days_idx = np.arange(7)
np.random.shuffle(days_idx)     # reorders the array IN PLACE
print("shuffled day order:", days_idx)

sample = np.random.choice(temps, size=3, replace=False)   # 3 random days, no repeats
print("random sample:     ", sample)

`np.random.choice(..., replace=False)` samples *without* repeats — the same idea as dealing
cards from a shuffled deck, rather than pulling from a deck that gets reshuffled after every card.

**Try it yourself:** use `days_idx` (once shuffled) to split `temps` into a 5-day "training" set and a
2-day "test" set — `temps[days_idx[:5]]` and `temps[days_idx[5:]]`.


In [ ]:
# Your code here


## Module 8 — np.where, argmax, argmin

### np.where is a vectorized if/else

`np.where(condition, value_if_true, value_if_false)` checks every element of an array and picks one
of two results for each — no loop needed.


In [5]:
label = np.where(temps > 24, "warm", "cool")
print("temps:", temps)
print("label:", label)

temps: [22 24 19 21 26 28 23]
label: ['cool' 'cool' 'cool' 'cool' 'warm' 'warm' 'cool']


Every element is checked in one shot: wherever `temps > 24` is `True`, take `"warm"`; otherwise
take `"cool"`. This replaces a loop with an if/else inside it.

### argmax / argmin: the position of the best value

`max()` tells you the biggest value. `argmax()` tells you *where* it is — the index. That index is
often what you actually need.


In [ ]:
print("biggest value:", temps.max())        # 28   -- the value itself
print("its position:  ", temps.argmax())     # 5    -- the index
print("which day:     ", days[temps.argmax()])  # 'Sat' -- look the index up

"Which day was hottest?" needs the *index*, not the value — `argmax` gives you the position you
can look up. This exact pattern is how a classifier turns raw scores into a decision:


In [ ]:
scores = np.array([0.1, 0.7, 0.2])      # a model's confidence in each class
labels = ["cat", "dog", "bird"]

predicted = labels[scores.argmax()]
print("predicted label:", predicted)        # "dog" -- the class with the highest score

A model outputs a score per class; `argmax` turns those scores into the single predicted label.
Same operation, different data, from a week of temperatures to a trained classifier's output.

**Try it yourself:** using `np.where`, build a `label` array that says `"hot"` for temps above 26,
`"mild"` for 22–26, and `"cool"` below 22. (Hint: you can nest two `np.where` calls.)


In [ ]:
# Your code here


## Module 9 — Transpose, Stacking, and Cleanup

### .T — swap rows and columns

Transposing swaps rows and columns. The values don't change — only the layout does. This matters
because some functions expect "samples as rows, features as columns," and your data won't always
arrive in that shape.


In [ ]:
print("grid.shape:  ", grid.shape)     # (3, 7)
print("grid.T.shape:", grid.T.shape)   # (7, 3)

### Stacking: combining several arrays into one

`np.vstack` stacks rows on top of each other — like adding a new city. `np.hstack` stacks columns
side by side — like adding a new day. `np.concatenate` does either, with an explicit `axis` argument.


In [ ]:
lalitpur = np.array([21, 23, 20, 22, 25, 27, 24])   # one more city's week

grid2 = np.vstack([grid, lalitpur])
print("grid2.shape:", grid2.shape)      # (4, 7) -- one more row
print(grid2)

### Cleanup: real data is messy

A handful of functions handle the untidy parts of real datasets: duplicate values, needing things in
order, and missing data.


In [ ]:
city_labels = np.array(["Kathmandu", "Kathmandu", "Pokhara", "Biratnagar", "Pokhara"])
print("unique cities:", np.unique(city_labels))

print("sorted temps:      ", np.sort(temps))          # values, smallest to largest, as a NEW array
print("argsort (indices): ", np.argsort(temps))        # the indices that WOULD sort it
print("temps by that order:", temps[np.argsort(temps)])  # using argsort to actually sort

In [ ]:
# Missing data: NaN ("Not a Number") represents a value that's absent
messy_temps = np.array([22, 24, np.nan, 21, 26, 28, 23])

print("plain mean:  ", messy_temps.mean())      # nan -- ONE missing value poisons the whole result
print("is it nan?   ", np.isnan(messy_temps))   # True/False per element
print("nan-safe mean:", np.nanmean(messy_temps))  # ignores the missing value instead

`np.nan` silently breaks ordinary `sum()`/`mean()` — a single missing value turns the whole
result into `nan`. The `nan`-aware versions (`np.nanmean`, `np.nansum`, `np.nanmax`, ...) skip missing
values instead of propagating them.

**Try it yourself:** `np.argsort(temps)[::-1]` sorts from *largest* to smallest instead. Use it to
print the three hottest days, in order, along with their day names.


In [ ]:
# Your code here


## Wrapping up · Part 2

Five more ideas to take with you:

- **Matrix multiplication (`@`)** multiplies pairs of numbers and adds them up — the operation inside
  linear regression and every neural network layer.
- **Aggregating along an axis**: `axis=N` is the dimension that disappears from the result. `sum`,
  `mean`, `max`, `min`, `std`, and `argmax` all take it.
- **Random numbers**: `np.random.seed` makes randomness reproducible; `shuffle` and `choice` build
  fair train/test splits.
- **np.where, argmax, argmin**: a vectorized if/else, and turning a set of scores into the index of
  the best one — the last step of a classifier.
- **Transpose, stacking, cleanup**: reshape data into the layout an operation needs, and handle
  duplicates, ordering, and missing values safely.

Together with Part 1, these nine ideas cover the NumPy you'll lean on most heavily for the rest of
this course — from here on, we'll be using them rather than teaching them.
